#!/bin/sh

##################
# fnaify 1.1
#
# created 2017-12-27
# by Thomas Frohwein (thfr)
# by Mariusz Zaborski (oshogbo)
#################
# Script to get FNA-based games
# ready to run on BSD
#
# FNA is a reimplementation of the Microsoft XNA Game Studio 4.0 Refresh libraries.
# Thanks to the great work by Ethan Lee (flibitijibibo) games using FNA are
# highly portable and can even run on BSD.
# Please refer to https://fna-xna.github.io/ for more information about FNA
##################
# License: ISC license
##################
# Requirements:
#
# - SDL2 library that identifies as 'Linux' rather than 'BSD'
#   (needs to be compiled this way; patch to recognize BSD in
#   progress upstream)
# - mono
# - some additional libraries, like mojoshader, theorafile, etc
##################
# Usage:
#
# fnaify [-v] [-h]
#
# -v: verbose output
# -h: print usage information
##########
# KNOWN BUGS:
#
###########
# TODO:
# - add notice about libatomstb?
# - provide a way to add in most recent FNA.dll?
#########

#########
# Status of different FNA.dll versions
#########

# Problematic FNA.dll versions:
# FNA.dll 15.12.21.0 (Apotheon)
# FNA.dll 0.0.0.1 (Adventures of Shuggy, Rex Rocket, Wizorb, Wyv and Keep)
# FNA.dll 16.1.0.0 (Brushwood)

# Working FNA.dll versions:

# MonoGame.Framework.dll 3.0.0.0 (AVNT, Capsized, EscapeGoat, Rogue Legacy, Soulcaster1&2)
# MonoGame.Framework.dll 3.1.2.0 (EscapeGoat2, Gateways, Skulls of the Shogun)
# FNA.dll 16.5.0.0 (Bleed, Super Rad Raygun)
# FNA.dll 16.7.0.0 (TowerFall: Ascension)
# FNA.dll 16.8.0.0 (Paladin, Shipwreck)
# FNA.dll 16.11.0.0 (FEZ)
# FNA.dll 16.12.0.0 (Overdriven Reloaded, Square Heroes)
# FNA.dll 17.2.0.0 (Hacknet)
# FNA.dll 17.3.0.0 (Salt&Sanctuary)
# FNA.dll 17.5.0.0 (Hidden in Plain Sight)
# FNA.dll 17.6.0.0 (Bleed2, Dust: An Elysian Tail, Press X to Not Die)
# FNA.dll 17.9.0.0 (Charlie Murder, The Dishwasher: Vampire Smile)
# FNA.dll 17.11.0.0 (Flinthook, RCRU) -- **Note: These 2 titles have stability issues. Unclear if this may be related to the FNA.dll version.**
# FNA.dll 17.12.0.0 (Curse of the Crescent Isle DX, Hyphen, Owlboy)


#########
# Argument parsing and Usage
#########

USAGE="Usage: `basename $0` -v -h"

while [ $# -gt 0 ]
do
	case "$1" in
		-h) echo $USAGE; exit 0;;
		-v) FNAIFY_DEBUG=1;;
	esac
	shift
done

#########
# VARIABLE AND FUNCTION DEFINITIONS
#########

SAVEIFS=$IFS
fna_warning=0

#monofilearray: array of mono files that need to be removed from the game folder
#ignoredarray: array of lib names to ignore for the configuration checking
#needlibarray[*] is the array that will hold the names of needed libraries
#foundlibarray[*] is the array of the libraries that were found to match
#                 needlibarray
#missinglibs[*] accumulates missing library names to inform user

debug_echo()
{
	if [ -z "$FNAIFY_DEBUG" ]; then
		return
	fi

	if [ "${1}" = '-n' ]; then
		printf "$2"
	else
		printf "$1\n"
	fi
}

debug_printdash()
{
	if [ -z "$FNAIFY_DEBUG" ]; then
		return
	fi

	printdash $*
}

# printdash: print $1 number of dashes in one line, followed by newline
printdash()
{
	c=1
	while [ $c -le $1 ]; do
		echo -n -
		c=$((c+1))
	done
	echo ""
}

# inarray: check if $1 is in array $2 (with simple grep)
inarray()
{
	firstarg="$1"
	shift 1
	echo "$*" | grep -q "$firstarg"
}

# validlib: returns 0 unless $1 is in ignoredarray, then returns 1
# FIXME: this won't be able to deal with whitespace at the moment
validlib()
{
	for ig in $ignoredarray; do
		if [ "${ig}" = "${1}" ]; then
			return 1
		fi
	done
	return 0
}

# trunklibnam: truncate the name of the library (and remove '-2.0') to match BSD
trunklibnam()
{
	libnam="$1"
	libnam="$(echo "$libnam" | sed -n -E "s/(.*\.so)\.?.*/\1/p")"
	libnam="$(echo "$libnam" | sed -E "s/(libSDL2[^-]*)-2\.0(\.so.*)/\1\2/")"
	echo "$libnam"
}


libraryname()
{
	version="$1"

	debug_echo ""
	if [ ! -e "$gamedir/$version" ]; then
		debug_echo "Couldn't find library directory $gamedir/$version"
	else
		debug_echo "Entering library directory $gamedir/$version"
		for file in $(ls "$gamedir/$version"); do
			# sort out libs (e.g. steam) that need to be ignored
			validlib $file
			if [ $? -eq 1 ]; then
				continue
			fi
			debug_echo -n "\tfound library file: $file"
			file=$(trunklibnam "$file")
			debug_echo " -> $file"
			inarray $file ${needlibarray}
			if [ $? -eq 0 ]; then
				debug_echo " - already in array"
			elif [ $? -eq 1 ]; then
				needlibarray="$needlibarray$file "
			else
				echo "\n\t - ERROR: inarray returned with unexpected error"
				echo ""
				exit 1
			fi
		done
		debug_echo "Done with library directory $gamedir/$version"
	fi
}

ignoredarray="libCSteamworks.so
libsteam_api.so
libSteamworksNative.so
libcef.so
libXNAWebRenderer.so
libSteamWrapper.so
libParisSteam.so
steamwrapper.so
libCommunityExpressSW.so
libXNAFileDialog.so
libfmod.so
libfmodstudio.so
libtiny_jpeg.so
libGalaxy64.so
libGalaxyCSharpGlue.so
libGalaxy.so"

monofilearray="System.dll
Mono.Posix.dll
Mono.Security.dll
System.Configuration.dll
System.Core.dll
System.Data.dll
System.Xml.dll
System.Security.dll
System.Runtime.Serialization.dll
mscorlib.dll
System.Drawing.dll
monoconfig
System.Xml.Linq.dll
WindowsBase.dll
monomachineconfig
I18N.CJK.dll
I18N.MidEast.dll
I18N.Other.dll
I18N.Rare.dll
I18N.West.dll
I18N.dll
Microsoft.CSharp.dll
Mono.CSharp.dll
System.ServiceModel.dll"

#######################################################################

#######
# MAIN SCRIPT
#######

gamedir="`pwd`"

echo ""

# scriptfilearray: array of files that are identified as a possible launchscript
debug_echo "Trying to identify the launch script file automatically..."

scount=0
scriptfilearray=""
sfile=""
IFS="
"
for sfile in $(find . -maxdepth 1 -type f | grep -Ev "\.[^/]|mono.*config$" | cut -f 2 -d "/")
do
	debug_echo "\tfound candidate for launch script file: $sfile"
	if [ -z "${scriptfilearray}" ]; then
		scriptfilearray="$sfile"
	else
		scriptfilearray="$scriptfilearray $sfile"
	fi
	scount=$((scount + 1))
done
IFS=$SAVEIFS

if [ $scount -gt 1 ]; then
	i=0
	for fsc in $scriptfilearray; do
		echo "$i: ${fsc}"
		i=$((i + 1))
	done
	echo -n "Enter number of the file to use as the launch script: "
	read input_script
	# XXXosho: Very, very ogly... but I don't care.
	i=0
	for fsc in $scriptfilearray; do
		echo "$i: ${fsc}"
		if [ $i -eq $input_script ]; then
			scriptfile="${fsc}"
			break
		fi
		i=$((i + 1))
	done
	if [ -z "${scriptfile}" ]; then
		echo "BAD NUMBER"
		exit 1
	fi
elif [ $scount -eq 1 ]; then
	scriptfile="$scriptfilearray"
else
	echo "WARNING: failed to identify a pre-existing launch script."
	echo -n "Please enter a name for the launch script to be created: "
	read scriptfile
fi

debug_echo "Identified the following file as the launch script: $scriptfile\n"

# path and file variable definitions
fullscriptpath="`pwd`/$scriptfile"
IFS="
"
exefile=""
nexefile=0
for xfile in $(ls "$gamedir" | grep "\.exe$"); do
	exefile="$exefile$xfile "
	nexefile=$((nexefile + 1))
done
IFS=$SAVEIFS

# configfilesarray: array of files in gamedir ending in '.config'
configfilesarray=""
nconfigfilesarray=0
debug_echo "Identifying config files..."
IFS="
"
for cfile in $(ls "$gamedir" | grep "\.config$"); do
	debug_echo "\tfound config file: $cfile"
	configfilesarray="$configfilesarray$cfile "
	nconfigfilesarray=$((nconfigfilesarray + 1))
done
IFS=$SAVEIFS
debug_echo "Done identifying config files.\n"

####
# identify required libraries
####
# - at the moment will check 3 sources: lib64, lib, and .config files
# - filenames not whitespace-safe, but should not be used in such files anyway
####

debug_echo "Identifying libraries required by the game..."
debug_printdash 45

# get library names from lib64 and lib folder
needlibarray=""
libraryname "lib64"
libraryname "lib"

# get library names from .config files
debug_echo "Obtaining library names from the following config files"

# check that configfilesarray isn't empty
if [ $nconfigfilesarray -lt 1 ]; then
	debug_echo "No config files found."
else
	cfile=""	# empty the variable because it has been used before
	for cfile in $configfilesarray; do
		debug_echo "\t$cfile"
		linuxlines=$(grep "os\=\"linux" "$gamedir/$cfile")
		# FIXME: this sed call would probably get messed up if there is
		#	whitespace
		for libstring in $(echo "$linuxlines" | sed -n -E "s/.*target=\"([^\"]+).*/\1/p")
		do
			# Fix where library name includes directory information
			# remove "./" at the beginning of librarynames
			libstring=$(echo "$libstring" | sed -E 's/^.\///')
			# remove directories at the start of lib name
			libstring=$(echo "$libstring" | sed -E 's/^.*\///')
			debug_echo -n "\t\tFound library string: $libstring"
			# sort out libs (e.g. steam) that need to be ignored
			validlib $libstring
			if [ $? -eq 1 ]; then
				debug_echo " - ignored"
				continue
			fi
			# truncate/fix SDL2 names{,s}
			libstring=$(trunklibnam "$libstring")
			debug_echo -n " -> $libstring"
			#needlibarray[${#needlibarray[*]} + 1]=$libstring
			# check if libstring is already in needlibarray.
			# add to needlibarray only if not.
			inarray $libstring $needlibarray
			if [ $? -eq 0 ]; then
				debug_echo " - already in array"
			elif [ $? -eq 1 ]; then
				needlibarray="$needlibarray$libstring "
				debug_echo " - added to array"
			else
				echo "\n\t - ERROR: inarray returned with unexpected error"
				echo ""
				exit 1
			fi
		done
	done
	debug_echo "Done with identifying libraries in config files"
fi
debug_echo "Done with identification of needed libraries."

# Fix libpngXX.so filename
# XXXosho: check that
debug_echo -n "Fixing libpng filenames if present..."
needlibarray=`echo "${needlibarray}" | sed -E "s/(libpng)..(\.so.*) /\1\2/"`
debug_echo " done.\n"

# Check if the libraries are available on the system (/usr/local/lib).
# If not, break and inform user which libraries need to be installed.
echo "Checking installed libraries..."

missinglibs=""
for needlib in ${needlibarray}; do
	if ls /usr/local/lib | grep -q "^$needlib"; then
		debug_echo "\tfound system lib for: $needlib"
	else
		if echo "$needlib" | grep -q 'libfreetype\.so.*' ; then
			debug_echo "\tfound libfreetype (see /usr/X11R6/lib)"
		else
			debug_echo "\tNot found: $needlib"
			missinglibs="$missinglibs$needlib "
		fi
	fi
done
debug_echo ""

# Check if mono is available
debug_echo -n "Checking that mono can be called..."
missingmono=0
#whence mono > /dev/null # XXXosho: not portable ;/
ls /usr/local/bin/mono > /dev/null # XXXosho: wierd idea
if [ $? -ne 0 ]; then
	echo " Couldn't find mono in PATH"
	missingmono=1
else
	debug_echo " Found mono.\n"
fi

# check version of framework library (FNA.dll or MonoGame.Framework.dll)
if [ $missingmono -lt 1 ]; then
	debug_echo "Checking version of framework library..."
	# FIXME: the following code assumes that only one of FNA.dll and MonoGame.Framework.dll is present
	if [ -e "$gamedir/FNA.dll" ]; then
		fnaversion=`monodis --assembly "$gamedir/FNA.dll" | grep "Version" | tr -d [:alpha:] | tr -d " " | tr -d \:`
		fnamajor=`echo "$fnaversion" | sed -n -E "s/\..*//p"`
		fnaminor=`echo "$fnaversion" | sed -n -E "s/[0-9]+\.([0-9]+)\.[0-9]+\.[0-9]+/\1/p"`
		debug_echo "\tFound FNA.dll version $fnaversion"
		debug_echo "fnamajor: $fnamajor"
		debug_echo "fnaminor: $fnaminor"
		if [ $fnamajor -lt 16 ] || ( [ $fnamajor -eq 16 ] && [ $fnaminor -lt 5 ] )
		then
			fna_warning=1
		fi
	elif [ -e "$gamedir/MonoGame.Framework.dll" ]
	then
		mgversion=`monodis --assembly "$gamedir/MonoGame.Framework.dll" | grep "Version" | tr -d [:alpha:] | tr -d " " | tr -d \:`
		debug_echo "\tFound MonoGame.Framework.dll version $mgversion"
	else
		echo "WARNING: Could not find framework library (FNA.dll or MonoGame.Framework.dll) in $gamedir"
	fi
else
	debug_echo "Can't check version of framework library because couldn't find mono"
fi
echo ""

echo -n "Result of configuration testing: "
if [ -n "${missinglibs}" -o "${missingmono}" -eq 1 ]; then
	echo "FAILED"
	printdash 39

	echo "The following requirements were not met:"
	if [ $missingmono -eq 1 ]; then
		echo -n - -
		echo " Could not find 'mono' in PATH"
	fi
	if [ -z "${missinglibs}" ]; then
		echo -n - -
		echo " Could not find library: $missinglibs"
	fi
	echo ""
	exit 1
fi
echo "SUCCESS"
debug_printdash 40

####
# replace all occurences of 'linux' in .config files (dllmap) with 'openbsd'
#    (this won't be needed after fna 18.01+ rolled out)

echo ""
echo "Adjusting config files for BSD..."

# create backup .linux files of the original .config files
debug_echo -n "\t(creating copy of original config files with suffix '.linux')... "
IFS="
"
for file in $(ls "$gamedir" | grep "\.config$")
do
	if [ ! -e "$gamedir/$file.linux" ]; then
		cp -p "$gamedir/$file" "$gamedir/$file.linux"
	fi
done
IFS=$SAVEIFS
debug_echo "done."

# replace all terms in *.config
IFS="
"
for file in $(ls "$gamedir" | grep "\.config$")
do
	# someone may be able to provide a more compact solution for this section
	# remove "./" at the beginning of any target="..."
	sed -i -E 's/target=".\//target="/g' "$gamedir/$file"
	# remove directory lib{,64} at the start of any target="..."
	sed -i -E 's/target="lib64\//target="/g' "$gamedir/$file"
	sed -i -E 's/target="lib\//target="/g' "$gamedir/$file"
	sed -i -E 's/os="linux/os="freebsd/g' "$gamedir/$file"
	# remove suffix numbers
	sed -i -E 's/\(target=".*\).so.*"/\1.so"/g' "$gamedir/$file"
	# fix SDL2 naming by removing the '-2.0'
	sed -i -E 's/target="libSDL2-2.0.so/target="libSDL2.so/g' "$gamedir/$file"
	# FIXME: find out where 'dll=' is used with .so and how often
	# 	(there was an example with libfreetype in this place somewhere)
#XXXosho:	sed -i -E 's/(dll="lib[a-zA-Z]*\.so)[\.0-9]*(.*)$/\1\2/g' "$gamedir/$file"
done
IFS=$SAVEIFS
debug_echo "Config files adjusted."

# Move interfering mono files out of the way
debug_echo -n "Moving some bundled dll files into linux-files subfolder... "
for file in $monofilearray; do
	if [ -e "$gamedir/$file" ]; then
		debug_echo "Found bundled mono file: $file"
		if [ ! -e "$gamedir/linux-files" ]
		then
			mkdir "$gamedir/linux-files"
		fi
		mv "$gamedir/$file" "$gamedir/linux-files"
	fi
done
debug_echo " done."

###
# create wrapper script in the game folder, set correct .exe in script, and set to executable

if [ $nexefile -gt 1 ]; then
	i=0
	for ex in $exefile; do
		echo "$i: $ex"
		i=$((i + 1))
	done
	echo -n "Enter number of .exe file to choose for wrapper script: "
	read input_script
	# XXXosho: Very, very ogly... but I don't care.
	i=0
	for ex in $exefile; do
		echo "$i: ${fsc}"
		if [ $i -eq $input_script ]; then
			selectexe="${ex}"
			break
		fi
		i=$((i + 1))
	done
	if [ -z "${selectexe}" ]; then
		echo "BAD NUMBER"
		exit 1
	fi
elif [ $nexefile -eq 1 ]; then
	selectexe="$exefile"
else
	echo "ERROR: no .exe file found"
	echo ""
	exit 1
fi

echo "Replacing launcher script with BSD variant..."
# if not exists, make backup of original script for linux
debug_echo -n "\t(creating copy of original launcher script with suffix '.linux')... "
if [ ! -e "$fullscriptpath.linux" ]
then
	cp -p "$fullscriptpath" "$fullscriptpath.linux"
fi
debug_echo "done."

exe_flags=""
exe_env=""

ls "$gamedir" | fgrep -iqm 1 "hacknet"
case $? in
	0) exe_flags="-disableweb";;
	1) ;;
	*) print "Error in running 'ls | fgrep'"; exit 1;;
esac

ls "$gamedir" | fgrep -iqm 1 "wizorb"
case $? in
	0) exe_env="MONO_IOMAP=all";;
	1) ;;
	*) print "Error in running 'ls | fgrep'"; exit 1;;
esac

# The content of the wrapper script
cat <<EOF > $fullscriptpath
#!/bin/sh

# fnaify wrapper script for launching FNA games on BSD

# run mono with LD_LIBRARY_PATH to find native BSD libraries
LD_LIBRARY_PATH=/usr/local/lib $exe_env mono $selectexe $exe_flags \$*
EOF

chmod +x "$fullscriptpath"

debug_echo "Launcher script replaced.\n"
debug_echo "SETUP COMPLETE"
debug_printdash 14

echo ""
echo "You should now be able to start the game by running:"
echo ""
echo "\$ ./$scriptfile"
echo ""

if [ $fna_warning -eq 1 ]
then
	echo "WARNING: version of FNA.dll potentially incompatble!"
	echo "If unable to launch with this version, consider replacing with newer version."
	echo "Source available at https://github.com/FNA-XNA/FNA/releases"
	echo ""
fi
